In [1]:
aws_sales=pd.read_excel("AWS_Sales.xlsx",
    sheet_name="aws_sales")

customers = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="customers"
)
calendar = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="calendar"
)
territories = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="territories"
)
products_cat = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="products_cat"
)
products_subcat = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="products_subcat"
)
products = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="products"
)
returns = pd.read_excel(
    "AWS_Sales.xlsx",
    sheet_name="returns"
)
product_master = (
    products
    .merge(
        products_subcat,
        on='ProductSubcategoryKey',
        how='left'
    )
    .merge(
        products_cat,
        on='ProductCategoryKey',
        how='left'
    )
)
sales_master=(
    aws_sales.merge(customers,on='CustomerKey',how='left')
    .merge(product_master,on='ProductKey',how='left')
    .merge(territories,left_on='TerritoryKey',right_on='SalesTerritoryKey',how='left')
)

C:\Users\shukl\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.4' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\shukl\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
sales_master.columns

Index(['Source.Name', 'OrderDate', 'StockDate', 'OrderNumber', 'ProductKey',
       'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity',
       'QuanityType', 'RelatedPrice', 'RelatedDayName', 'Sales', 'Prefix',
       'FirstName', 'LastName', 'FullName', 'BirthDate', 'MaritalStatus',
       'Gender', 'EmailAddress', 'AnnualIncome', 'TotalChildren',
       'EducationLevel', 'Occupation', 'HomeOwner', 'UserName', 'DomainName',
       'BirthYear_CC', 'CurrentAge', 'BirthMonth', 'Parent', 'Full_Name_CC',
       'ProductSubcategoryKey', 'ProductSKU', 'ProductName', 'ModelName',
       'ProductDescription', 'ProductColor', 'ProductSize', 'ProductStyle',
       'ProductCost', 'ProductPrice', 'Discounted_Price',
       'Profit_Before_Discount', 'Profit_After_Discount', 'SubcategoryName',
       'ProductCategoryKey', 'CategoryName', 'SalesTerritoryKey', 'Region',
       'Country', 'Continent'],
      dtype='str')

In [3]:
# Feature Enginnering
#Feature 1- Age Group
sales_master['Agegroup']=pd.cut(sales_master['CurrentAge'],bins=[45,55,65,75,120],
labels=['46-55','56-65','66-75','75+'])

In [4]:
#Feature 2- Income Group
sales_master['IncomeGroup']=pd.cut(sales_master['AnnualIncome'],bins=[0,40000,80000,200000],
labels=['Low Income','Medium Income','High Income'])

In [5]:
sales_master['AnnualIncome'].describe()

count     56046.000000
mean      59761.089105
std       33074.125510
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       80000.000000
max      170000.000000
Name: AnnualIncome, dtype: float64

In [6]:
sales_master['CurrentAge'].describe()

count    56046.000000
mean        64.350890
std         11.013478
min         46.000000
25%         56.000000
50%         63.000000
75%         72.000000
max        116.000000
Name: CurrentAge, dtype: float64

In [7]:
sales_master.sort_values('CurrentAge',ascending=False)[['CustomerKey','FullName','CurrentAge']]

       CustomerKey         FullName  CurrentAge
44970        12725  Gabrielle James         116
20565        12725  Gabrielle James         116
41290        12725  Gabrielle James         116
31382        16455       Deb Moreno         115
12683        14841     Franklin Pal         115
...            ...              ...         ...
55039        11356  Terrence Carson          46
21098        18314       Eric Perry          46
29559        18314       Eric Perry          46
4946         13039        Trisha Ma          46
52209        28729      Heather Sun          46

[56046 rows x 3 columns]

In [8]:
sales_master.loc[sales_master['CurrentAge'] > 100, ['CustomerKey','FullName','CurrentAge']].drop_duplicates()

       CustomerKey           FullName  CurrentAge
4693         25978       Morgan Perez         101
9850         15519     Jennifer Evans         105
10771        20866        David Jones         104
11061        14992      Dale Andersen         114
11974        15075        Alexa Kelly         106
12683        14841       Franklin Pal         115
12952        21057   Elizabeth Butler         101
13006        22453        Dakota Long         104
13508        17640        Haley Allen         110
16968        26355       Darren Madan         101
17767        28743         Kelly Wood         111
17950        15628   Brianna Sandberg         110
17966        19430        Sharon Goel         106
17974        16471      Vanessa Hayes         113
18063        18034     Ethan Robinson         114
19113        25416       Jack Coleman         107
20037        20865          Luis Ross         104
20289        24713      Jeremy Brooks         110
20510        16563    Mackenzie Baker         107
20565        12725    Gabrielle James         116
20661        24836    Taylor Robinson         101
20789        14166  Elizabeth Jenkins         104
20820        14768          Ian Kelly         102
21143        17619        Chloe Smith         103
21496        26314       Angel Murphy         108
21609        16455         Deb Moreno         115
22465        24035          Jaclyn Wu         107
22962        23190  Nathaniel Ramirez         105
23281        16568   Caroline Coleman         104
23398        11845      Natalie Jones         102
23504        23208       Janet Watson         102
23885        16325      Emma Williams         113
24548        25325       Wyatt Parker         108
24577        22629  Matthew Rodriguez         103
24836        25527     Robert Johnson         113
25112        21684     Mariah Bennett         109

In [9]:
#Feature 3- Order Year
sales_master['OrderDate']=pd.to_datetime(sales_master['OrderDate'])
sales_master['OrderYear']=(sales_master['OrderDate'].dt.year)

In [10]:
#Feature 4- Quarter
sales_master['Quarter']=(sales_master['OrderDate'].dt.quarter)

In [11]:
#Feature 5- Manth Name
sales_master['MonthName']=(sales_master['OrderDate'].dt.month_name())

In [12]:
#Feature 6- Manth Number
sales_master['MonthNumber'] = (
    sales_master['OrderDate'].dt.month
)

In [13]:
sales_master

,Source.Name,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity,QuanityType,...,SalesTerritoryKey,Region,Country,Continent,Agegroup,IncomeGroup,OrderYear,Quarter,MonthName,MonthNumber
0,AdventureWorks_Sales_2016.csv,2016-01-03,2002-09-06,SO48819,352,13622,9,1,1,SingleItem,...,9,Australia,Australia,Pacific,46-55,Medium Income,2016,1,January,1
1,AdventureWorks_Sales_2016.csv,2016-01-13,2002-09-19,SO48901,352,13960,9,1,1,SingleItem,...,9,Australia,Australia,Pacific,56-65,Medium Income,2016,1,January,1
2,AdventureWorks_Sales_2016.csv,2016-01-14,2002-09-22,SO48909,352,13953,9,1,1,SingleItem,...,9,Australia,Australia,Pacific,56-65,High Income,2016,1,January,1
3,AdventureWorks_Sales_2016.csv,2016-01-16,2002-10-23,SO48929,352,13526,9,1,1,SingleItem,...,9,Australia,Australia,Pacific,46-55,Low Income,2016,1,January,1
4,AdventureWorks_Sales_2016.csv,2016-01-17,2002-12-17,SO48936,352,13644,9,1,1,SingleItem,...,9,Australia,Australia,Pacific,56-65,High Income,2016,1,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56041,AdventureWorks_Sales_2017.csv,2017-05-16,2004-02-16,SO70714,491,16916,5,7,1,SingleItem,...,5,Southeast,United States,North America,56-65,High Income,2017,2,May,5
56042,AdventureWorks_Sales_2017.csv,2017-06-01,2004-04-12,SO71961,214,12863,8,7,1,SingleItem,...,8,Germany,Germany,Europe,46-55,Low Income,2017,2,June,6
56043,AdventureWorks_Sales_2017.csv,2017-06-11,2004-04-11,SO72656,223,15614,10,8,2,MultipleItem,...,10,United Kingdom,United Kingdom,Europe,46-55,Low Income,2017,2,June,6
56044,AdventureWorks_Sales_2017.csv,2017-06-11,2004-05-27,SO72656,235,15614,10,7,1,SingleItem,...,10,United Kingdom,United Kingdom,Europe,46-55,Low Income,2017,2,June,6
56045,AdventureWorks_Sales_2017.csv,2017-06-14,2004-05-14,SO72927,229,26299,1,7,1,SingleItem,...,1,Northwest,United States,North America,46-55,Medium Income,2017,2,June,6

In [14]:
sales_master.to_csv("sales_master_processed.csv",index=False)

In [10]:
df=pd.read_csv("sales_master_processed.csv")

In [12]:
df.shape

(56046, 59)